notify-update: true
sound:
  enable: true
  type: AMBIENT_WARPED_FOREST_MOOD
  volume: 1.5
  pitch: 1.0
particle:
  enable: true
  type: SOUL
  offsetX: 0.6
  offsetY: 0.7
  offsetZ: 0.6
  count: 50
cooldown: 40
fishing:
  COD:
    enable: true
    chance: 0.02
  SALMON:
    enable: true
    chance: 0.02
entity-death:
  CHICKEN:
    enable: true
    chance: 0.02
  COD:
    enable: true
    chance: 0.02
  COW:
    enable: true
    chance: 0.02
  PIG:
    enable: true
    chance: 0.02
  RABBIT:
    enable: true
    chance: 0.02
  SHEEP:
    enable: true
    chance: 0.02
  SALMON:
    enable: true
    chance: 0.02
