notify-update: true
sound:
  enable: true
  type: AMBIENT_WARPED_FOREST_MOOD
  volume: 1.5
  pitch: 1.0
particle:
  enable: true
  type: SOUL
  offsetX: 0.6
  offsetY: 0.7
  offsetZ: 0.6
  count: 75
cooldown: 40
luck-of-the-sea-increase-chance: true
looting-increase-chance: true
fishing:
  COD:
    enable: true
    chance: 0.002
  SALMON:
    enable: true
    chance: 0.002
entity-death:
  CHICKEN:
    enable: true
    chance: 0.002
  COD:
    enable: true
    chance: 0.002
  COW:
    enable: true
    chance: 0.002
  PIG:
    enable: true
    chance: 0.002
  RABBIT:
    enable: true
    chance: 0.002
  SALMON:
    enable: true
    chance: 0.002
  SHEEP:
    enable: true
    chance: 0.002
